apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: local-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  path: /mnt/data
